# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat/reaction_v2/reaction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from chat.user_v2 import user_pb2 as chat_dot_user__v2_dot_user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63hat/reaction_v2/reaction.proto\x12\x17stream.chat.reaction_v2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x17\x63hat/user_v2/user.proto\"\xdf\x01\n\x08Reaction\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x30\n\nmessage_id\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x03\x12\x13\n\x0b\x63ustom_json\x18\x05 \x01(\x0c\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"l\n\x0cReactionView\x12\x33\n\x08reaction\x18\x01 \x01(\x0b\x32!.stream.chat.reaction_v2.Reaction\x12\'\n\x04user\x18\x02 \x01(\x0b\x32\x19.stream.chat.user_v2.User\"I\n\rReactionViews\x12\x38\n\treactions\x18\x01 \x03(\x0b\x32%.stream.chat.reaction_v2.ReactionViewBLZJgithub.com/GetStream/stream-services/protobuf/chat/reaction_v2;reaction_v2b\x06proto3')



_REACTION = DESCRIPTOR.message_types_by_name['Reaction']
_REACTIONVIEW = DESCRIPTOR.message_types_by_name['ReactionView']
_REACTIONVIEWS = DESCRIPTOR.message_types_by_name['ReactionViews']
Reaction = _reflection.GeneratedProtocolMessageType('Reaction', (_message.Message,), {
  'DESCRIPTOR' : _REACTION,
  '__module__' : 'chat.reaction_v2.reaction_pb2'
  # @@protoc_insertion_point(class_scope:stream.chat.reaction_v2.Reaction)
  })
_sym_db.RegisterMessage(Reaction)

ReactionView = _reflection.GeneratedProtocolMessageType('ReactionView', (_message.Message,), {
  'DESCRIPTOR' : _REACTIONVIEW,
  '__module__' : 'chat.reaction_v2.reaction_pb2'
  # @@protoc_insertion_point(class_scope:stream.chat.reaction_v2.ReactionView)
  })
_sym_db.RegisterMessage(ReactionView)

ReactionViews = _reflection.GeneratedProtocolMessageType('ReactionViews', (_message.Message,), {
  'DESCRIPTOR' : _REACTIONVIEWS,
  '__module__' : 'chat.reaction_v2.reaction_pb2'
  # @@protoc_insertion_point(class_scope:stream.chat.reaction_v2.ReactionViews)
  })
_sym_db.RegisterMessage(ReactionViews)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZJgithub.com/GetStream/stream-services/protobuf/chat/reaction_v2;reaction_v2'
  _REACTION._serialized_start=151
  _REACTION._serialized_end=374
  _REACTIONVIEW._serialized_start=376
  _REACTIONVIEW._serialized_end=484
  _REACTIONVIEWS._serialized_start=486
  _REACTIONVIEWS._serialized_end=559
# @@protoc_insertion_point(module_scope)
