name: stream_chat_persistence
homepage: https://github.com/GetStream/stream-chat-flutter
description: Official Stream Chat Persistence library. Build your own chat experience using Dart and Flutter.
version: 5.1.0
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  drift: ^1.5.0
  flutter:
    sdk: flutter
  logging: ^1.0.1
  meta: ^1.3.0
  mutex: ^3.0.0
  path: ^1.8.0
  path_provider: ^2.0.1
  sqlite3_flutter_libs: ^0.5.0
  stream_chat:
    git:
      url: https://github.com/zeeshan-rsys/stream-chat-flutter.git
      ref: develop
      path: packages/stream_chat/
dev_dependencies:
  build_runner: ^2.0.1
  dart_code_metrics: ^4.4.0
  drift_dev: ^1.5.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
