# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat/utils_v2/utils.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63hat/utils_v2/utils.proto\x12\x14stream.chat.utils_v2\"&\n\x05Pager\x12\r\n\x05limit\x18\x01 \x01(\x03\x12\x0e\n\x06offset\x18\x02 \x01(\x03\"I\n\x04Sort\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x32\n\tdirection\x18\x02 \x01(\x0e\x32\x1f.stream.chat.utils_v2.Direction*V\n\tDirection\x12\x19\n\x15\x44IRECTION_UNSPECIFIED\x10\x00\x12\x1b\n\x0e\x44IRECTION_DESC\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x11\n\rDIRECTION_ASC\x10\x01\x42\x46ZDgithub.com/GetStream/stream-services/protobuf/chat/utils_v2;utils_v2b\x06proto3')

_DIRECTION = DESCRIPTOR.enum_types_by_name['Direction']
Direction = enum_type_wrapper.EnumTypeWrapper(_DIRECTION)
DIRECTION_UNSPECIFIED = 0
DIRECTION_DESC = -1
DIRECTION_ASC = 1


_PAGER = DESCRIPTOR.message_types_by_name['Pager']
_SORT = DESCRIPTOR.message_types_by_name['Sort']
Pager = _reflection.GeneratedProtocolMessageType('Pager', (_message.Message,), {
  'DESCRIPTOR' : _PAGER,
  '__module__' : 'chat.utils_v2.utils_pb2'
  # @@protoc_insertion_point(class_scope:stream.chat.utils_v2.Pager)
  })
_sym_db.RegisterMessage(Pager)

Sort = _reflection.GeneratedProtocolMessageType('Sort', (_message.Message,), {
  'DESCRIPTOR' : _SORT,
  '__module__' : 'chat.utils_v2.utils_pb2'
  # @@protoc_insertion_point(class_scope:stream.chat.utils_v2.Sort)
  })
_sym_db.RegisterMessage(Sort)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZDgithub.com/GetStream/stream-services/protobuf/chat/utils_v2;utils_v2'
  _DIRECTION._serialized_start=166
  _DIRECTION._serialized_end=252
  _PAGER._serialized_start=51
  _PAGER._serialized_end=89
  _SORT._serialized_start=91
  _SORT._serialized_end=164
# @@protoc_insertion_point(module_scope)
