// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: chat/user_v2/user.proto

package user_v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushProvider int32

const (
	PushProvider_PUSH_PROVIDER_UNSPECIFIED PushProvider = 0
	PushProvider_PUSH_PROVIDER_FIREBASE    PushProvider = 1
	PushProvider_PUSH_PROVIDER_APN         PushProvider = 2
	PushProvider_PUSH_PROVIDER_HUAWEI      PushProvider = 3
	PushProvider_PUSH_PROVIDER_XIAOMI      PushProvider = 4
)

// Enum value maps for PushProvider.
var (
	PushProvider_name = map[int32]string{
		0: "PUSH_PROVIDER_UNSPECIFIED",
		1: "PUSH_PROVIDER_FIREBASE",
		2: "PUSH_PROVIDER_APN",
		3: "PUSH_PROVIDER_HUAWEI",
		4: "PUSH_PROVIDER_XIAOMI",
	}
	PushProvider_value = map[string]int32{
		"PUSH_PROVIDER_UNSPECIFIED": 0,
		"PUSH_PROVIDER_FIREBASE":    1,
		"PUSH_PROVIDER_APN":         2,
		"PUSH_PROVIDER_HUAWEI":      3,
		"PUSH_PROVIDER_XIAOMI":      4,
	}
)

func (x PushProvider) Enum() *PushProvider {
	p := new(PushProvider)
	*p = x
	return p
}

func (x PushProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_user_v2_user_proto_enumTypes[0].Descriptor()
}

func (PushProvider) Type() protoreflect.EnumType {
	return &file_chat_user_v2_user_proto_enumTypes[0]
}

func (x PushProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushProvider.Descriptor instead.
func (PushProvider) EnumDescriptor() ([]byte, []int) {
	return file_chat_user_v2_user_proto_rawDescGZIP(), []int{0}
}

// Chat user model
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique identifier of the User.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// User's role in the permission system.
	Role string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	// Contains information about user's online status.
	OnlineStatus *UserOnlineStatus `protobuf:"bytes,3,opt,name=online_status,json=onlineStatus,proto3" json:"online_status,omitempty"`
	// Contains information about user's ban status.
	Ban *UserBanStatus `protobuf:"bytes,4,opt,name=ban,proto3" json:"ban,omitempty"`
	// List of teams user is a part of.
	Teams []string `protobuf:"bytes,5,rep,name=teams,proto3" json:"teams,omitempty"`
	// Preferred language of a user.
	Language string `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	// custom is a JSON object which contains any user data.
	// in JSON encoded messages it will be represented as base64 encoded bytes
	CustomJson []byte `protobuf:"bytes,7,opt,name=custom_json,json=customJson,proto3" json:"custom_json,omitempty"`
	// Date of creation of the user.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Date of last update of user's data.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Date of deletion of the user.
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	// Date of deactivation of the user.
	DeactivatedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=deactivated_at,json=deactivatedAt,proto3" json:"deactivated_at,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_user_v2_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_chat_user_v2_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_chat_user_v2_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetOnlineStatus() *UserOnlineStatus {
	if x != nil {
		return x.OnlineStatus
	}
	return nil
}

func (x *User) GetBan() *UserBanStatus {
	if x != nil {
		return x.Ban
	}
	return nil
}

func (x *User) GetTeams() []string {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *User) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *User) GetCustomJson() []byte {
	if x != nil {
		return x.CustomJson
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *User) GetDeactivatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeactivatedAt
	}
	return nil
}

// Contains information about user's online status.
type UserOnlineStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Whether the user is online.
	Online bool `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	// Timestamp of the last activity.
	LastActiveAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_active_at,json=lastActiveAt,proto3" json:"last_active_at,omitempty"`
	// Invisibility condition of the user.
	// Setting this field to true will cause the user to be marked as offline
	// This field is not visible to other users
	Invisible *wrapperspb.BoolValue `protobuf:"bytes,3,opt,name=invisible,proto3" json:"invisible,omitempty"`
}

func (x *UserOnlineStatus) Reset() {
	*x = UserOnlineStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_user_v2_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOnlineStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOnlineStatus) ProtoMessage() {}

func (x *UserOnlineStatus) ProtoReflect() protoreflect.Message {
	mi := &file_chat_user_v2_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOnlineStatus.ProtoReflect.Descriptor instead.
func (*UserOnlineStatus) Descriptor() ([]byte, []int) {
	return file_chat_user_v2_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserOnlineStatus) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *UserOnlineStatus) GetLastActiveAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActiveAt
	}
	return nil
}

func (x *UserOnlineStatus) GetInvisible() *wrapperspb.BoolValue {
	if x != nil {
		return x.Invisible
	}
	return nil
}

// Contains information about user's ban status.
type UserBanStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Whether the user is banned.
	Banned bool `protobuf:"varint,1,opt,name=banned,proto3" json:"banned,omitempty"`
	// Time when the user will be unbanned.
	BanExpiresAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ban_expires_at,json=banExpiresAt,proto3" json:"ban_expires_at,omitempty"`
}

func (x *UserBanStatus) Reset() {
	*x = UserBanStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_user_v2_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBanStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBanStatus) ProtoMessage() {}

func (x *UserBanStatus) ProtoReflect() protoreflect.Message {
	mi := &file_chat_user_v2_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBanStatus.ProtoReflect.Descriptor instead.
func (*UserBanStatus) Descriptor() ([]byte, []int) {
	return file_chat_user_v2_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserBanStatus) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

func (x *UserBanStatus) GetBanExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BanExpiresAt
	}
	return nil
}

type UserOwnView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User         *User                          `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	PushSettings *UserPushNotificationsSettings `protobuf:"bytes,2,opt,name=push_settings,json=pushSettings,proto3" json:"push_settings,omitempty"`
	Unread       *UserUnreadStatus              `protobuf:"bytes,3,opt,name=unread,proto3" json:"unread,omitempty"`
}

func (x *UserOwnView) Reset() {
	*x = UserOwnView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_user_v2_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOwnView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOwnView) ProtoMessage() {}

func (x *UserOwnView) ProtoReflect() protoreflect.Message {
	mi := &file_chat_user_v2_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOwnView.ProtoReflect.Descriptor instead.
func (*UserOwnView) Descriptor() ([]byte, []int) {
	return file_chat_user_v2_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserOwnView) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserOwnView) GetPushSettings() *UserPushNotificationsSettings {
	if x != nil {
		return x.PushSettings
	}
	return nil
}

func (x *UserOwnView) GetUnread() *UserUnreadStatus {
	if x != nil {
		return x.Unread
	}
	return nil
}

type UserSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Push *UserPushNotificationsSettings `protobuf:"bytes,2,opt,name=push,proto3" json:"push,omitempty"`
}

func (x *UserSettings) Reset() {
	*x = UserSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_user_v2_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettings) ProtoMessage() {}

func (x *UserSettings) ProtoReflect() protoreflect.Message {
	mi := &file_chat_user_v2_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettings.ProtoReflect.Descriptor instead.
func (*UserSettings) Descriptor() ([]byte, []int) {
	return file_chat_user_v2_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserSettings) GetPush() *UserPushNotificationsSettings {
	if x != nil {
		return x.Push
	}
	return nil
}

type UserPushNotificationsSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Disabled      bool                   `protobuf:"varint,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	DisabledUntil *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=disabled_until,json=disabledUntil,proto3" json:"disabled_until,omitempty"`
	Devices       []*UserPushDevice      `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
}

func (x *UserPushNotificationsSettings) Reset() {
	*x = UserPushNotificationsSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_user_v2_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPushNotificationsSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPushNotificationsSettings) ProtoMessage() {}

func (x *UserPushNotificationsSettings) ProtoReflect() protoreflect.Message {
	mi := &file_chat_user_v2_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPushNotificationsSettings.ProtoReflect.Descriptor instead.
func (*UserPushNotificationsSettings) Descriptor() ([]byte, []int) {
	return file_chat_user_v2_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserPushNotificationsSettings) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *UserPushNotificationsSettings) GetDisabledUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.DisabledUntil
	}
	return nil
}

func (x *UserPushNotificationsSettings) GetDevices() []*UserPushDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type UserPushDevice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PushProvider     PushProvider `protobuf:"varint,2,opt,name=push_provider,json=pushProvider,proto3,enum=stream.chat.user_v2.PushProvider" json:"push_provider,omitempty"`
	PushProviderName string       `protobuf:"bytes,3,opt,name=push_provider_name,json=pushProviderName,proto3" json:"push_provider_name,omitempty"`
}

func (x *UserPushDevice) Reset() {
	*x = UserPushDevice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_user_v2_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPushDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPushDevice) ProtoMessage() {}

func (x *UserPushDevice) ProtoReflect() protoreflect.Message {
	mi := &file_chat_user_v2_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPushDevice.ProtoReflect.Descriptor instead.
func (*UserPushDevice) Descriptor() ([]byte, []int) {
	return file_chat_user_v2_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserPushDevice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserPushDevice) GetPushProvider() PushProvider {
	if x != nil {
		return x.PushProvider
	}
	return PushProvider_PUSH_PROVIDER_UNSPECIFIED
}

func (x *UserPushDevice) GetPushProviderName() string {
	if x != nil {
		return x.PushProviderName
	}
	return ""
}

type UserUnreadStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnreadMessageCount  int64 `protobuf:"varint,1,opt,name=unread_message_count,json=unreadMessageCount,proto3" json:"unread_message_count,omitempty"`
	UnreadChannelsCount int64 `protobuf:"varint,2,opt,name=unread_channels_count,json=unreadChannelsCount,proto3" json:"unread_channels_count,omitempty"`
}

func (x *UserUnreadStatus) Reset() {
	*x = UserUnreadStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_user_v2_user_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserUnreadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUnreadStatus) ProtoMessage() {}

func (x *UserUnreadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_chat_user_v2_user_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUnreadStatus.ProtoReflect.Descriptor instead.
func (*UserUnreadStatus) Descriptor() ([]byte, []int) {
	return file_chat_user_v2_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserUnreadStatus) GetUnreadMessageCount() int64 {
	if x != nil {
		return x.UnreadMessageCount
	}
	return 0
}

func (x *UserUnreadStatus) GetUnreadChannelsCount() int64 {
	if x != nil {
		return x.UnreadChannelsCount
	}
	return 0
}

// TODO: Q/A Do we need these data below?
//
type UserLatest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserLatest) Reset() {
	*x = UserLatest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_user_v2_user_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLatest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLatest) ProtoMessage() {}

func (x *UserLatest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_user_v2_user_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLatest.ProtoReflect.Descriptor instead.
func (*UserLatest) Descriptor() ([]byte, []int) {
	return file_chat_user_v2_user_proto_rawDescGZIP(), []int{8}
}

type UserMute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserMute) Reset() {
	*x = UserMute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_user_v2_user_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMute) ProtoMessage() {}

func (x *UserMute) ProtoReflect() protoreflect.Message {
	mi := &file_chat_user_v2_user_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMute.ProtoReflect.Descriptor instead.
func (*UserMute) Descriptor() ([]byte, []int) {
	return file_chat_user_v2_user_proto_rawDescGZIP(), []int{9}
}

type UserChannelMute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserChannelMute) Reset() {
	*x = UserChannelMute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_user_v2_user_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserChannelMute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChannelMute) ProtoMessage() {}

func (x *UserChannelMute) ProtoReflect() protoreflect.Message {
	mi := &file_chat_user_v2_user_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChannelMute.ProtoReflect.Descriptor instead.
func (*UserChannelMute) Descriptor() ([]byte, []int) {
	return file_chat_user_v2_user_proto_rawDescGZIP(), []int{10}
}

var File_chat_user_v2_user_proto protoreflect.FileDescriptor

var file_chat_user_v2_user_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x76, 0x32, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x76, 0x32, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xf3, 0x03, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x4a, 0x0a, 0x0d,
	0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x76, 0x32, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0c, 0x6f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x34, 0x0a, 0x03, 0x62, 0x61, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x76, 0x32, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x42, 0x61, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x03, 0x62, 0x61, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x65, 0x61, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4a, 0x73, 0x6f,
	0x6e, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x41, 0x0a, 0x0e, 0x64, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x64, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xa6, 0x01, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x12, 0x40, 0x0a, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x09, 0x69, 0x6e, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x22, 0x69,
	0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x12, 0x40, 0x0a, 0x0e, 0x62, 0x61, 0x6e, 0x5f, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x62, 0x61, 0x6e,
	0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x22, 0xd4, 0x01, 0x0a, 0x0b, 0x55, 0x73,
	0x65, 0x72, 0x4f, 0x77, 0x6e, 0x56, 0x69, 0x65, 0x77, 0x12, 0x2d, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x76, 0x32, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x57, 0x0a, 0x0d, 0x70, 0x75, 0x73, 0x68,
	0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x32, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x76, 0x32, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x52, 0x0c, 0x70, 0x75, 0x73, 0x68, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x12, 0x3d, 0x0a, 0x06, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x25, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x76, 0x32, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x55, 0x6e, 0x72, 0x65,
	0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64,
	0x22, 0x56, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x12, 0x46, 0x0a, 0x04, 0x70, 0x75, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32,
	0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x76, 0x32, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x52, 0x04, 0x70, 0x75, 0x73, 0x68, 0x22, 0xbd, 0x01, 0x0a, 0x1d, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x75, 0x73, 0x68, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x41, 0x0a, 0x0e, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x5f, 0x75, 0x6e, 0x74, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x64, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x55, 0x6e, 0x74, 0x69, 0x6c, 0x12, 0x3d, 0x0a, 0x07, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x76, 0x32,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x96, 0x01, 0x0a, 0x0e, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x75, 0x73, 0x68, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x46, 0x0a, 0x0d, 0x70,
	0x75, 0x73, 0x68, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x21, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x76, 0x32, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x0c, 0x70, 0x75, 0x73, 0x68, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x12, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x10, 0x70, 0x75, 0x73, 0x68, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x78, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x30, 0x0a, 0x14, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x12, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x15, 0x75, 0x6e, 0x72, 0x65, 0x61,
	0x64, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x0c, 0x0a, 0x0a, 0x55,
	0x73, 0x65, 0x72, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x22, 0x0a, 0x0a, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x4d, 0x75, 0x74, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x4d, 0x75, 0x74, 0x65, 0x2a, 0x94, 0x01, 0x0a, 0x0c, 0x50, 0x75, 0x73,
	0x68, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x19, 0x50, 0x55, 0x53,
	0x48, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x50, 0x55, 0x53, 0x48,
	0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x46, 0x49, 0x52, 0x45, 0x42, 0x41,
	0x53, 0x45, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x55, 0x53, 0x48, 0x5f, 0x50, 0x52, 0x4f,
	0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x41, 0x50, 0x4e, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x50,
	0x55, 0x53, 0x48, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x48, 0x55, 0x41,
	0x57, 0x45, 0x49, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x55, 0x53, 0x48, 0x5f, 0x50, 0x52,
	0x4f, 0x56, 0x49, 0x44, 0x45, 0x52, 0x5f, 0x58, 0x49, 0x41, 0x4f, 0x4d, 0x49, 0x10, 0x04, 0x42,
	0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x76, 0x32, 0x3b, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chat_user_v2_user_proto_rawDescOnce sync.Once
	file_chat_user_v2_user_proto_rawDescData = file_chat_user_v2_user_proto_rawDesc
)

func file_chat_user_v2_user_proto_rawDescGZIP() []byte {
	file_chat_user_v2_user_proto_rawDescOnce.Do(func() {
		file_chat_user_v2_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_chat_user_v2_user_proto_rawDescData)
	})
	return file_chat_user_v2_user_proto_rawDescData
}

var file_chat_user_v2_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chat_user_v2_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_chat_user_v2_user_proto_goTypes = []interface{}{
	(PushProvider)(0),                     // 0: stream.chat.user_v2.PushProvider
	(*User)(nil),                          // 1: stream.chat.user_v2.User
	(*UserOnlineStatus)(nil),              // 2: stream.chat.user_v2.UserOnlineStatus
	(*UserBanStatus)(nil),                 // 3: stream.chat.user_v2.UserBanStatus
	(*UserOwnView)(nil),                   // 4: stream.chat.user_v2.UserOwnView
	(*UserSettings)(nil),                  // 5: stream.chat.user_v2.UserSettings
	(*UserPushNotificationsSettings)(nil), // 6: stream.chat.user_v2.UserPushNotificationsSettings
	(*UserPushDevice)(nil),                // 7: stream.chat.user_v2.UserPushDevice
	(*UserUnreadStatus)(nil),              // 8: stream.chat.user_v2.UserUnreadStatus
	(*UserLatest)(nil),                    // 9: stream.chat.user_v2.UserLatest
	(*UserMute)(nil),                      // 10: stream.chat.user_v2.UserMute
	(*UserChannelMute)(nil),               // 11: stream.chat.user_v2.UserChannelMute
	(*timestamppb.Timestamp)(nil),         // 12: google.protobuf.Timestamp
	(*wrapperspb.BoolValue)(nil),          // 13: google.protobuf.BoolValue
}
var file_chat_user_v2_user_proto_depIdxs = []int32{
	2,  // 0: stream.chat.user_v2.User.online_status:type_name -> stream.chat.user_v2.UserOnlineStatus
	3,  // 1: stream.chat.user_v2.User.ban:type_name -> stream.chat.user_v2.UserBanStatus
	12, // 2: stream.chat.user_v2.User.created_at:type_name -> google.protobuf.Timestamp
	12, // 3: stream.chat.user_v2.User.updated_at:type_name -> google.protobuf.Timestamp
	12, // 4: stream.chat.user_v2.User.deleted_at:type_name -> google.protobuf.Timestamp
	12, // 5: stream.chat.user_v2.User.deactivated_at:type_name -> google.protobuf.Timestamp
	12, // 6: stream.chat.user_v2.UserOnlineStatus.last_active_at:type_name -> google.protobuf.Timestamp
	13, // 7: stream.chat.user_v2.UserOnlineStatus.invisible:type_name -> google.protobuf.BoolValue
	12, // 8: stream.chat.user_v2.UserBanStatus.ban_expires_at:type_name -> google.protobuf.Timestamp
	1,  // 9: stream.chat.user_v2.UserOwnView.user:type_name -> stream.chat.user_v2.User
	6,  // 10: stream.chat.user_v2.UserOwnView.push_settings:type_name -> stream.chat.user_v2.UserPushNotificationsSettings
	8,  // 11: stream.chat.user_v2.UserOwnView.unread:type_name -> stream.chat.user_v2.UserUnreadStatus
	6,  // 12: stream.chat.user_v2.UserSettings.push:type_name -> stream.chat.user_v2.UserPushNotificationsSettings
	12, // 13: stream.chat.user_v2.UserPushNotificationsSettings.disabled_until:type_name -> google.protobuf.Timestamp
	7,  // 14: stream.chat.user_v2.UserPushNotificationsSettings.devices:type_name -> stream.chat.user_v2.UserPushDevice
	0,  // 15: stream.chat.user_v2.UserPushDevice.push_provider:type_name -> stream.chat.user_v2.PushProvider
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_chat_user_v2_user_proto_init() }
func file_chat_user_v2_user_proto_init() {
	if File_chat_user_v2_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chat_user_v2_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_user_v2_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOnlineStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_user_v2_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBanStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_user_v2_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOwnView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_user_v2_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_user_v2_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPushNotificationsSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_user_v2_user_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPushDevice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_user_v2_user_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserUnreadStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_user_v2_user_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLatest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_user_v2_user_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_user_v2_user_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserChannelMute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chat_user_v2_user_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_user_v2_user_proto_goTypes,
		DependencyIndexes: file_chat_user_v2_user_proto_depIdxs,
		EnumInfos:         file_chat_user_v2_user_proto_enumTypes,
		MessageInfos:      file_chat_user_v2_user_proto_msgTypes,
	}.Build()
	File_chat_user_v2_user_proto = out.File
	file_chat_user_v2_user_proto_rawDesc = nil
	file_chat_user_v2_user_proto_goTypes = nil
	file_chat_user_v2_user_proto_depIdxs = nil
}
