# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat/server_v2_rpc/rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63hat/server_v2_rpc/rpc.proto\x12\x19stream.chat.server_v2_rpc2\x0b\n\tServerRPCBPZNgithub.com/GetStream/stream-services/protobuf/chat/server_v2_rpc;server_v2_rpcb\x06proto3')



_SERVERRPC = DESCRIPTOR.services_by_name['ServerRPC']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZNgithub.com/GetStream/stream-services/protobuf/chat/server_v2_rpc;server_v2_rpc'
  _SERVERRPC._serialized_start=59
  _SERVERRPC._serialized_end=70
# @@protoc_insertion_point(module_scope)
