# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat/client_v2_rpc/rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chat.client_v2_rpc import channel_pb2 as chat_dot_client__v2__rpc_dot_channel__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63hat/client_v2_rpc/rpc.proto\x12\x19stream.chat.client_v2_rpc\x1a chat/client_v2_rpc/channel.proto2\xea\x01\n\tClientRPC\x12i\n\nGetChannel\x12,.stream.chat.client_v2_rpc.GetChannelRequest\x1a-.stream.chat.client_v2_rpc.GetChannelResponse\x12r\n\rQueryChannels\x12/.stream.chat.client_v2_rpc.QueryChannelsRequest\x1a\x30.stream.chat.client_v2_rpc.QueryChannelsResponseBPZNgithub.com/GetStream/stream-services/protobuf/chat/client_v2_rpc;client_v2_rpcb\x06proto3')



_CLIENTRPC = DESCRIPTOR.services_by_name['ClientRPC']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZNgithub.com/GetStream/stream-services/protobuf/chat/client_v2_rpc;client_v2_rpc'
  _CLIENTRPC._serialized_start=94
  _CLIENTRPC._serialized_end=328
# @@protoc_insertion_point(module_scope)
